server:
  port: 9191
  context-path: /h2
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  h2:
    console:
      path: /console
      enabled: true